force-app/main/default/objects/Secured_Field_Access_Log__c/Secured_Field_Access_Log__c.object-meta.xml
<CustomObject>
    <description>Secured Field Access Log</description>
    <label>Secured Field Access Log</label>
    <nameField>
        <displayFormat>L{0000000000}</displayFormat>
        <label>Secured Field Access Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secured Field Access Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>View</fullName>
                <default>true</default>
                <label>View</label>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Secured_Field_Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SecuredFieldAccessLogger.cls
public with sharing class SecuredFieldAccessLogger implements Callable {
    public static String logView(String objectName, String fieldName, String recordId, String detail) {
        try {
            Secured_Field_Access_Log__c sfal = new Secured_Field_Access_Log__c();
            sfal.Object_Name__c = objectName;
            sfal.Field_Name__c = fieldName;
            sfal.User__c = UserInfo.getUserId();
            sfal.Record_Id__c = recordId;
            sfal.Mode__c = 'View';
            sfal.Details__c = detail;
            insert sfal;
        } catch (Exception e) {
            return 'Error! ' + e.getMessage();
        }

        return 'Success';
    }

    // Dispatch actual methods
    public Object call(String action, Map<String, Object> args) {
        switch on action {
            when 'logView' {
                return SecuredFieldAccessLogger.logView((String) args.get('objectName'),
                                                        (String) args.get('fieldName'),
                                                        (String) args.get('recordId'),
                                                        (String) args.get('detail'));
            }
            when else {
                throw new ExtensionMalformedCallException('Method not implemented');
            }
        }
    }

    public class ExtensionMalformedCallException extends Exception {}

}