force-app/main/default/objects/Secured_Field_Access_Log__c/Secured_Field_Access_Log__c.object-meta.xml
<CustomObject>
    <description>Secured Field Access Log</description>
    <label>Secured Field Access Log</label>
    <nameField>
        <displayFormat>L{0000000000}</displayFormat>
        <label>Secured Field Access Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secured Field Access Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>View</fullName>
                <default>true</default>
                <label>View</label>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Secured_Field_Access_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Secured_Field_Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SecuredFieldAccessLoggerTest.cls
@isTest
private class SecuredFieldAccessLoggerTest {
    @isTest static void testLogView() {

        Callable logger = (Callable) Type.forName('SecuredFieldAccessLogger').newInstance();
        String status = (String) logger.call('logView', 
                                             new Map<String, Object> { 'objectName' => 'DummyObject', 
                                                                       'fieldName' => 'DummyField', 
                                                                       'recordId' => 'DummyRecord',
                                                                       'detail' => 'Dummy Detail' });
        
        System.assertEquals('Success', status);

        list<Secured_Field_Access_Log__c> sfal = [select Object_Name__c,
                                                        Field_Name__c, 
                                                        User__c,
                                                        Record_Id__c,
                                                        Mode__c,
                                                        Details__c
                                                from Secured_Field_Access_Log__c];
        System.assertEquals(1, sfal.size());
        System.assertEquals('DummyObject', sfal[0].Object_Name__c);
        System.assertEquals('DummyField', sfal[0].Field_Name__c);
        System.assertEquals('DummyRecord', sfal[0].Record_Id__c);
        System.assertEquals('Dummy Detail', sfal[0].Details__c);
        System.assertEquals('View', sfal[0].Mode__c);
        System.assertEquals(UserInfo.getUserId(), sfal[0].User__c);
    }

    @isTest static void testLogChange() {

        Callable logger = (Callable) Type.forName('SecuredFieldAccessLogger').newInstance();
        String status = (String) logger.call('logChange', 
                                             new Map<String, Object> { 'objectName' => 'DummyObject', 
                                                                       'fieldName' => 'DummyField', 
                                                                       'recordId' => 'DummyRecord',
                                                                       'detail' => 'Dummy Detail' });
        
        System.assertEquals('Success', status);

        list<Secured_Field_Access_Log__c> sfal = [select Object_Name__c,
                                                        Field_Name__c, 
                                                        User__c,
                                                        Record_Id__c,
                                                        Mode__c,
                                                        Details__c
                                                from Secured_Field_Access_Log__c];
        System.assertEquals(1, sfal.size());
        System.assertEquals('DummyObject', sfal[0].Object_Name__c);
        System.assertEquals('DummyField', sfal[0].Field_Name__c);
        System.assertEquals('DummyRecord', sfal[0].Record_Id__c);
        System.assertEquals('Dummy Detail', sfal[0].Details__c);
        System.assertEquals('View', sfal[0].Mode__c);
        System.assertEquals(UserInfo.getUserId(), sfal[0].User__c);
    }
}